version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 0
layout:

  /overlay/:
    -
      - menu-6682
    -
      - blockcontent-3824
    -
      - social-6445

  /navigation/:
    -
      - 'logo-8536 75'
      - 'custom-3022 5'
      - 'overlaytoggle-8711 20'
    -
      - 'position-navigation-a 33.3'
      - 'position-navigation-b 33.3'
      - 'position-navigation-c 33.3'
  /top/:
    -
      - system-messages-8159
    -
      - 'position-top-a 33.3'
      - 'position-top-b 33.3'
      - 'position-top-c 33.3'
  /header/:
    -
      - 'position-header-a 33.3'
      - 'position-header-b 33.3'
      - 'position-header-c 33.3'
  /slideshow/:
    -
      - position-slideshow
  /showcase/:
    -
      - 'position-showcase-a 33.3'
      - 'position-showcase-b 33.3'
      - 'position-showcase-c 33.3'
  /above/:
    -
      - 'position-above-a 33.3'
      - 'position-above-b 33.3'
      - 'position-above-c 33.3'
  /utility/:
    -
      - 'position-utility-a 33.3'
      - 'position-utility-b 33.3'
      - 'position-utility-c 33.3'
  /feature/:
    -
      - 'position-feature-a 33.3'
      - 'position-feature-b 33.3'
      - 'position-feature-c 33.3'
  /container-main/:
    -
      -
        'sidebar 20':
          -
            - position-sidebar
      -
        'mainbar 60':
          -
            - 'position-mainbar-a 33.3'
            - 'position-mainbar-b 33.3'
            - 'position-mainbar-c 33.3'
          -
            - system-content-5020
      -
        'aside 20':
          -
            - position-aside
  /expanded/:
    -
      - 'position-expanded-a 33.3'
      - 'position-expanded-b 33.3'
      - 'position-expanded-c 33.3'
  /extension/:
    -
      - 'position-extension-a 33.3'
      - 'position-extension-b 33.3'
      - 'position-extension-c 33.3'
  /bottom/:
    -
      - 'position-bottom-a 33.3'
      - 'position-bottom-b 33.3'
      - 'position-bottom-c 33.3'
  /footer/:
    -
      - 'position-footer-a 25'
      - 'position-footer-b 25'
      - 'position-footer-c 25'
      - 'position-footer-d 25'
  /copyright/:
    -
      - 'branding-3018 33.3'
      - 'copyright-5323 33.3'
      - 'totop-8334 33.3'
  /offcanvas/:
    -
      - mobile-menu-8402
structure:
  navigation:
    type: section
    attributes:
      class: g-headroom
      boxed: ''
  top:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      extra:
        -
          data-enllax-ratio: '0.4'
        -
          data-enllax-type: background
      boxed: ''
  slideshow:
    type: section
    attributes:
      boxed: '2'
  showcase:
    type: section
    attributes:
      boxed: ''
  above:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
  mainbar:
    type: section
  container-main:
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  extension:
    type: section
    attributes:
      extra:
        -
          data-enllax-ratio: '0.3'
        -
          data-enllax-type: background
      boxed: ''
  bottom:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  blockcontent-3824:
    title: 'Block Content'
    attributes:
      class: 'center g-overlay-blockcontent'
      title: 'Keep in Touch'
      description: 'Have a suggestion, comment, or question? Drop us a line and we''ll reply you soon!'
      subcontents:
        -
          name: Email
          icon: 'fa fa-envelope-o'
          img: ''
          rokboximage: ''
          rokboxcaption: ''
          subtitle: ''
          description: hi@isotope-g5.com
          class: box4
          button: ''
          buttonlink: ''
          buttonclass: ''
          title: Email
        -
          name: Phone
          icon: 'fa fa-phone'
          img: ''
          rokboximage: ''
          rokboxcaption: ''
          subtitle: ''
          description: +1-222-333555777
          class: box4
          button: ''
          buttonlink: ''
          buttonclass: ''
          title: Phone
        -
          name: Address
          icon: 'fa fa-paper-plane-o'
          img: ''
          rokboximage: ''
          rokboxcaption: ''
          subtitle: ''
          description: 'Isotope Building, 88, USA'
          class: box4
          button: ''
          buttonlink: ''
          buttonclass: ''
          title: Address
  logo-8536:
    attributes:
      text: 'Dalen Catt'
  custom-3022:
    title: 'Custom HTML'
    attributes:
      html: '<div class="g-offcanvas-toggle visible-phone" data-offcanvas-toggle aria-controls="g-offcanvas" aria-expanded="false"><i class="fa fa-fw fa-bars"></i></div>'
    block:
      class: visible-phone
      variations: 'nomarginall nopaddingall'
  overlaytoggle-8711:
    title: 'Overlay Toggle'
    attributes:
      menutext: Menu
    block:
      class: hidden-phone
  system-messages-8159:
    block:
      variations: 'nomarginall nopaddingall'
  position-top-a:
    title: 'Top A'
  position-top-b:
    title: 'Top B'
  position-top-c:
    title: 'Top C'
  position-navigation-a:
    title: 'Navigation A'
  position-navigation-b:
    title: 'Navigation B'
  position-navigation-c:
    title: 'Navigation C'
  position-header-a:
    title: 'Header A'
  position-header-b:
    title: 'Header B'
  position-header-c:
    title: 'Header C'
  position-showcase-a:
    title: 'Showcase A'
  position-showcase-b:
    title: 'Showcase B'
  position-showcase-c:
    title: 'Showcase C'
  position-above-a:
    title: 'Above A'
  position-above-b:
    title: 'Above B'
  position-above-c:
    title: 'Above C'
  position-utility-a:
    title: 'Utility A'
  position-utility-b:
    title: 'Utility B'
  position-utility-c:
    title: 'Utility C'
  position-feature-a:
    title: 'Feature A'
  position-feature-b:
    title: 'Feature B'
  position-feature-c:
    title: 'Feature C'
  position-mainbar-a:
    title: 'Mainbar A'
  position-mainbar-b:
    title: 'Mainbar B'
  position-mainbar-c:
    title: 'Mainbar C'
  position-expanded-a:
    title: 'Expanded A'
  position-expanded-b:
    title: 'Expanded B'
  position-expanded-c:
    title: 'Expanded C'
  position-extension-a:
    title: 'Extension A'
  position-extension-b:
    title: 'Extension B'
  position-extension-c:
    title: 'Extension C'
  position-bottom-a:
    title: 'Bottom A'
  position-bottom-b:
    title: 'Bottom B'
  position-bottom-c:
    title: 'Bottom C'
  position-footer-a:
    title: 'Footer A'
    block:
      class: g-title-bordered
  position-footer-b:
    title: 'Footer B'
    block:
      class: g-title-bordered
  position-footer-c:
    title: 'Footer C'
    block:
      class: g-title-bordered
  position-footer-d:
    title: 'Footer D'
  branding-3018:
    attributes:
      content: 'Powered by <a href="http://www.gantry.org/" title="Gantry Framework" class="g-powered-by">Gantry<span class="hidden-tablet"> Framework</span></a>'
  totop-8334:
    title: 'To Top'
    attributes:
      icon: 'fa fa-arrow-circle-o-up fa-2x'
      content: ''
  mobile-menu-8402:
    title: 'Mobile Menu'
